### ISSUE TITLE
Implement `Depth` function

### ISSUE THREAD

**Issue by schomatis** [nikkolasg/drg-attacks#2]
The implementation in C# seems pretty straightforward so we should do that.

https://github.com/filecoin-project/PebblingAndDepthReductionAttacks/blob/master/ConsoleApplication1/Helpers.cs#L1773-L1796

**Comment by nikkolasg** [comment]
Impl. in https://github.com/nikkolasg/drg-attacks/commit/18229b4b94a9aee931e88895772d5882a5d27cc5
