### ISSUE TITLE
Implement basic Valiant attack

### ISSUE THREAD

**Issue by schomatis** [nikkolasg/drg-attacks#3]
Needed in #1.

The C# code could be used as a guide although it seems unnecesary compliated. The [`BuildDepthReducingSetValiantHelper`](https://github.com/filecoin-project/PebblingAndDepthReductionAttacks/blob/master/ConsoleApplication1/Helpers.cs#L1191) method (which seem like the basic case) used in [`DepthReducingSetValiant`](https://github.com/filecoin-project/PebblingAndDepthReductionAttacks/blob/d03b0b93f16bbf5d643b3876574db610a07e4797/ConsoleApplication1/Helpers.cs#L1116) doesn't keep track of the current `E_i` (`i` being the number of bits "taken out" of the original edge set `E` and moved to `S` to reduce its depth) so it seems to recalculate it in each iteration.

**Comment by nikkolasg** [comment]
Impl. in https://github.com/nikkolasg/drg-attacks/commit/2382f9d209057452c4003344944e8d5cfbe69242
