### ISSUE TITLE
Implement MSDB

### ISSUE THREAD

**Issue by schomatis** [nikkolasg/drg-attacks#5]
Needed in #3.

The C# code has a more general variant which allows to set any base, not just 2, which doesn't seem worth the complexity at this point. I would take the code [there](https://github.com/filecoin-project/PebblingAndDepthReductionAttacks/blob/master/ConsoleApplication1/Helpers.cs#L1168), hardcoding `bbase` as 2 and removing the resulting redundant logic from it.

**Comment by nikkolasg** [comment]
impl. in https://github.com/nikkolasg/drg-attacks/commit/e5276540f06dd6713c904cd75fc4e67953548209
